resourceLimits:
  -resourceType: 'cpu'
  minimum: 4
  maximum: 10
  -resourceType: 'memory'
  maximum: 64
  -resourceType: 'nvidia-tesla-k80'
  maximum: 4
management:
  autoRepair: true
  autoUpgrade: true
shieldedInstanceConfig:
  enableSecureBoot: true
  enableIntegrityMonitoring: true
diskSizeGb: 32